spring:
  application:
    name: restaurant

  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties.hibernate.format_sql: true

logging:
  level:
    feign:
      client: true

server:
  port: 8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeOut: 5000
        loggerLevel: FULL

users-service:
  url: http://localhost:8090